// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/service-transaction.proto

package proto

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ServiceTransaction service

func NewServiceTransactionEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ServiceTransaction service

type ServiceTransactionService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (ServiceTransaction_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (ServiceTransaction_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (ServiceTransaction_BidiStreamService, error)
}

type serviceTransactionService struct {
	c    client.Client
	name string
}

func NewServiceTransactionService(name string, c client.Client) ServiceTransactionService {
	return &serviceTransactionService{
		c:    c,
		name: name,
	}
}

func (c *serviceTransactionService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "ServiceTransaction.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceTransactionService) ClientStream(ctx context.Context, opts ...client.CallOption) (ServiceTransaction_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "ServiceTransaction.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &serviceTransactionServiceClientStream{stream}, nil
}

type ServiceTransaction_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type serviceTransactionServiceClientStream struct {
	stream client.Stream
}

func (x *serviceTransactionServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *serviceTransactionServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *serviceTransactionServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *serviceTransactionServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *serviceTransactionServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *serviceTransactionServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *serviceTransactionService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (ServiceTransaction_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "ServiceTransaction.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &serviceTransactionServiceServerStream{stream}, nil
}

type ServiceTransaction_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type serviceTransactionServiceServerStream struct {
	stream client.Stream
}

func (x *serviceTransactionServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *serviceTransactionServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *serviceTransactionServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *serviceTransactionServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *serviceTransactionServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *serviceTransactionServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serviceTransactionService) BidiStream(ctx context.Context, opts ...client.CallOption) (ServiceTransaction_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "ServiceTransaction.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &serviceTransactionServiceBidiStream{stream}, nil
}

type ServiceTransaction_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type serviceTransactionServiceBidiStream struct {
	stream client.Stream
}

func (x *serviceTransactionServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *serviceTransactionServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *serviceTransactionServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *serviceTransactionServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *serviceTransactionServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *serviceTransactionServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *serviceTransactionServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for ServiceTransaction service

type ServiceTransactionHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, ServiceTransaction_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, ServiceTransaction_ServerStreamStream) error
	BidiStream(context.Context, ServiceTransaction_BidiStreamStream) error
}

func RegisterServiceTransactionHandler(s server.Server, hdlr ServiceTransactionHandler, opts ...server.HandlerOption) error {
	type serviceTransaction interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type ServiceTransaction struct {
		serviceTransaction
	}
	h := &serviceTransactionHandler{hdlr}
	return s.Handle(s.NewHandler(&ServiceTransaction{h}, opts...))
}

type serviceTransactionHandler struct {
	ServiceTransactionHandler
}

func (h *serviceTransactionHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.ServiceTransactionHandler.Call(ctx, in, out)
}

func (h *serviceTransactionHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.ServiceTransactionHandler.ClientStream(ctx, &serviceTransactionClientStreamStream{stream})
}

type ServiceTransaction_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type serviceTransactionClientStreamStream struct {
	stream server.Stream
}

func (x *serviceTransactionClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *serviceTransactionClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *serviceTransactionClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *serviceTransactionClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *serviceTransactionClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *serviceTransactionHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ServiceTransactionHandler.ServerStream(ctx, m, &serviceTransactionServerStreamStream{stream})
}

type ServiceTransaction_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type serviceTransactionServerStreamStream struct {
	stream server.Stream
}

func (x *serviceTransactionServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *serviceTransactionServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *serviceTransactionServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *serviceTransactionServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *serviceTransactionServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *serviceTransactionHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.ServiceTransactionHandler.BidiStream(ctx, &serviceTransactionBidiStreamStream{stream})
}

type ServiceTransaction_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type serviceTransactionBidiStreamStream struct {
	stream server.Stream
}

func (x *serviceTransactionBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *serviceTransactionBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *serviceTransactionBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *serviceTransactionBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *serviceTransactionBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *serviceTransactionBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
